name: flutter_band_fit_app
description: Demonstrates how to use the flutter_band_fit plugin.
version: 0.0.1+1
publish_to: 'none'

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  flutter_band_fit:
    path: ../

  cupertino_icons: ^1.0.9
  intl: ^0.20.2
  http: ^1.6.0
  get: ^4.7.3
  infinite_scroll_pagination: ^5.1.1
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  get_storage: ^2.1.1
  syncfusion_flutter_charts: ^33.2.7
  health: ^13.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fit/
    - assets/logo.png
