include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - example/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false

    always_declare_return_types: true
    strict_top_level_inference: true
    type_annotate_public_apis: true

    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    public_member_api_docs: true
